# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  test-and-save-cov:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0

      # Run tests script
      - name: Run all tests
        uses: matlab-actions/run-command@v0
#        continue-on-error: true
        with:
          command: addpath('tests'); run_tests

      # Upload coverage report
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml

      # Throw error if tests failed
      - name: Check if tests failed
        uses: matlab-actions/run-command@v0
        with:
          command: load('test_results', 'result'); assertSuccess(result);
